version: '2'
services:

  logstash:
    build:
      context: .
      dockerfile: Dockerfile
    image: sciensa/logstash-cloudhub:1.3.0
    command: >
      logstash --debug -e '
        input {
          cloudhub {
            username => "leogaona_gerdau"
            password => "L30n@rd0"
            organization_id => "6ea8d099-1d3c-4645-b89c-a199d002eefc"
            environment_name => "Development"
          }
        } output { stdout {} }'
