version: '2'
services:

  logstash:
    build:
      context: .
      dockerfile: Dockerfile
    image: sciensa/logstash-cloudhub:1.2.0
    command: >
      logstash --debug -e '
        input {
          cloudhub {
            username => "${CLOUDHUB_USERNAME}"
            password => "${CLOUDHUB_PASSWORD}"
            organization_id => "${CLOUDHUB_ORGANIZATION_ID}"
            environment_name => "${ENV_NAME}"
            environment_id => "${CLOUDHUB_ENV_ID}"
          }
        } output { stdout {} }'
