version: '2'
services:

  logstash:
    build:
      context: .
      dockerfile: Dockerfile
    image: sciensa/logstash-cloudhub:1.3.0
    command: >
      logstash --debug -e '
        input {
          cloudhub {
            username => "${CLOUDHUB_USERNAME}"
            password => ${CLOUDHUB_PASSWORD}"
            organization_id => "${CLOUDHUB_ORGANIZATION_ID}"
            environment_name => "${CLOUDHUB_ENV_NAME}"
          }
        }
        output {
          stdout {}
        }
      '
